import = [
  "~/.config/alacritty/themes/themes/github_dark_dimmed.toml"
]

[shell]
program = "tmux"
args = ["new-session", "-A", "-s", "default"]

[window]
opacity = 1
padding.x = 10
padding.y = 10
decorations = "None"
startup_mode = "maximized" 

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 15

[env]
term = "xterm-256color"
